import unittest
import requests

from yaml import load

class TestCreateIssue(unittest.TestCase):
    def setUp(self):
        self.settings = load(open('settings.yaml').read())
        self.base_url = self.settings['base_url']
        self.cookies = self._login()
        
    def _login(self):
        url = self.base_url + '/user/login'
        
        params = {
        'login': self.settings['credentials']['login'],
        'password': self.settings['credentials']['password']
        }
        
        r = requests.post(url, data=params)
        return r.cookies
        
    def test_create_issue(self):
        url = self.base_url + '/issue'
        params = {
        'project': 'api',
        'summary': 'Generated by robots',
        'description': 'Hail the robots!'
        }
        r = requests.put(url, data=params, cookies=self.cookies)
        self.assertEquals(r.status_code, 201)
        
        issue_id = r.headers['location'].split('/')[-1]
        
        url = self.base_url + '/issue/' + issue_id
        r = requests.get(url, cookies=self.cookies)
        self.assertEquals(r.status_code, 200)
        
    
        
       
        
    
    
    